server:
  #  port: 8771
  port: 8772

spring:
  application:
    name: order
#  datasource:
#    #    url: jdbc:mysql://192.168.1.94:3306/mccken201908?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/mccken201908?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: root
#    #    password: luo2010.
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 5000
#      filters: stat,wall
#
#      # druid 监控页面
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: root
#        login-password: root
#      web-stat-filter:
#        enabled: true
#        exclusions:
#          - "*.js"
#          - "*.gif"
#          - "*.jpg"
#          - "*.png"
#          - "*.css"
#          - "*.ico"
#          - "/druid/*"
#        #        principal-session-name: USER_SESSION
#        principal-cookie-name: USER_COOKIE
#        session-stat-enable: true
#      aop-patterns: com.mccken201908.order.dao.*

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mccken201908.order.model     