server:
  #    port: 8771
  port: 8772

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://192.168.1.94:3306/mccken201908?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000
      # 状态监控
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # 监控过滤器
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      # druid 监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: root
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    # 初始化大小，最小，最大
#    druid:
#      initial-size: 5
#      minIdle: 2
#      # 最大连接池个数
#      maxActive: 20
#      # 配置获取连接等待超时的时间，单位毫秒，缺省启用公平锁，并发效率会有所下降
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      # 用来检测连接是否有效的sql，要求是一个查询语句。
#      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
#      validationQuery: SELECT 1 FROM DUAL
#      # 建议配置为true，不影响性能，并且保证安全性。
#      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
#      testWhileIdle: true
#      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
#      testOnBorrow: false
#      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 通过别名的方式配置扩展插件，多个英文逗号分隔，常用的插件有： 
#      # 监控统计用的filter:stat
#      # 日志用的filter:log4j
#      # 防御sql注入的filter:wall
#      filters: StatFilter,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      # 合并多个DruidDataSource的监控数据
#      useGlobalDataSourceStat: true
#      stat-view-servlet:
#        enabled: true
#      filter:
#        stat:
#          enabled: true
#          log-slow-sql: true
#          db-type: mysql
#          slow-sql-millis: 2000
#          merge-sql: true
#        config:
#          enabled: true
#        encoding:
#          enabled: true
#        slf4j:
#          enabled: true
#          statement-create-after-log-enabled: false
#          statement-close-after-log-enabled: false
#          result-set-open-after-log-enabled: false
#          result-set-close-after-log-enabled: false



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mccken201908.order.model     