server:
  #  port: 8761
  port: 8962

eureka:
  instance:
    hostname: eureka1
  #    hostname: eureka2
  client:
    #    表示是否将自己注册到Eureka Server， 默认为true
    #    register-with-eureka: false
    #    表示是否从Eureka Server获取注册信息，默认为true
    #    fetch-registry: false
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            #      defaultZone: http://localhost:8762/eureka/
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-server